# Generated by Django 4.2.2 on 2023-06-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_service_image_service_icon_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=1, upload_to='projects/'),
            preserve_default=False,
        ),
    ]
